### -={ Auth }=- ###

### Auth SignIn
POST http://localhost:3000/auth/signIn
Content-Type: application/json

{
  "email": "email.example@gmail.com",
  "password": "signUp"
}

### Auth SignUp
POST http://localhost:3000/auth/signUp
Content-Type: application/json

{
  "name": "login",
  "email": "email.exampfcle@gmail.com",
  "password": "signUp"
}

### Auth forgot password
POST http://localhost:3000/auth/forgot-password
Content-Type: application/json

{
  "email": "lucas1511gll@gmail.com"
}

### Auth reset password
POST http://localhost:3000/auth/recover
Content-Type: application/json

{
  "token": "59123065-686e-4146-971c-3e978702d439",
  "password": "560065",
  "confirmPassword": "560065"
}

### Auth logout
POST http://localhost:3000/auth/logout
Content-Type: application/json

{
  "userId": "ad8aa7ce-c48f-4497-b300-e4b06330e868",
  "refreshToken": "fb8ca7b6-3180-4508-a9de-068d64d23caf"
}


### -={ User }=- ###

### User get
GET http://localhost:3000/user/profile
Authorization: Bearer

### User update
PATCH http://localhost:3000/user/profile
Content-Type: application/json
Authorization: Bearer

{
  "name": "Luis"
}

### User delete
DELETE http://localhost:3000/user/profile
Content-Type: application/json
Authorization: Bearer
{
  "password": ""
}


### -={ ADMIN }=- ###

### Admin get all
GET http://localhost:3000/admin/all
Authorization: Bearer

### Admin get one | (id)
GET http://localhost:3000/admin/
Authorization: Bearer

### Admin create new user
POST http://localhost:3000/admin/add
Content-Type: application/json
Authorization: Bearer

{
  "name": "TEST2",
  "email": "email2@test.com",
  "password": "test12",
  "role": "USER"
}

### Admin patch | (id)
PATCH http://localhost:3000/admin/
Content-Type: application/json
Authorization: Bearer

{
  "role": "ADMIN"
}


### Admin delete | (id)
DELETE http://localhost:3000/admin/
Authorization: Bearer


### -={ Task }=- ###

### Admin find all task
GET http://localhost:3000/admin/task/all/
Authorization: Bearer

### Admin find all task by user | (userId)
GET http://localhost:3000/admin/task/all/
Authorization: Bearer

### Admin find task by id | (taskId)
GET http://localhost:3000/admin/task/
Authorization: Bearer

### Admin create task for user | (userId)
POST http://localhost:3000/admin/task/
Content-Type: application/json
Authorization: Bearer

{
  "title": "nuclear material"
}

### Admin update task by id | (taskId)
PATCH http://localhost:3000/admin/task/
Content-Type: application/json
Authorization: Bearer

{
  "title": "change"
}

### Admin delete task by id | (taskId)
DELETE http://localhost:3000/admin/task/
Authorization: Bearer


# ------------------------------------------------------------------------ #


### User find all task
GET http://localhost:3000/user/task/my-tasks
Authorization: Bearer

### User create task
POST http://localhost:3000/user/task
Content-Type: application/json
Authorization: Bearer

{
  "title": "user test"
}

### User update task | (taskId)
PATCH http://localhost:3000/user/task/
Content-Type: application/json
Authorization: Bearer

{
  "title": "user tests"
}

### User delete task | (taskId)
DELETE http://localhost:3000/user/task/
Authorization: Bearer
