### User ###

### Create user
POST http://localhost:3000/user
Content-Type: application/json

{
  "name": "Lucas Lima",
  "email": "lucas@example.com",
  "password": "password123"
}

### Find user
GET http://localhost:3000/user/lucas@example.com

### Delete user
DELETE http://localhost:3000/user/

### Auth ###

### Auth SignIn
POST http://localhost:3000/auth/signIn
Content-Type: application/json

{
  "email": "lucas@example.com",
  "password": "password123"
}

### Auth SignUp
POST http://localhost:3000/auth/signUp
Content-Type: application/json

{
  "name": "Luis",
  "email": "luis@test.com",
  "password": "password123"
}
