### -={ User | Task }=- ###

### User find all task
GET http://localhost:3000/user/task
Authorization: Bearer

### User find task by id | (taskId)
GET http://localhost:3000/user/task/
Authorization: Bearer

### User search task | (searchText)
GET http://localhost:3000/user/task/search?q=testar%20api
Authorization: Bearer 

### User create task
POST http://localhost:3000/user/task
Content-Type: application/json
Authorization: Bearer

{
  "title": ""
}

### User update task | (taskId)
PATCH http://localhost:3000/user/task/
Content-Type: application/json
Authorization: Bearer

{
  "title": "nuclear craft"
}

### User delete task | (taskId)
DELETE http://localhost:3000/user/task/
Authorization: Bearer
