### -={ Auth }=- ###

### Auth SignIn
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "lucas1511gll@gmail.com",
  "password": "560065"
}

### Auth SignUp
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "name": "Lanza",
  "email": "lucas1511gll@gmail.com",
  "password": "560065"
}

### Auth forgot password
POST http://localhost:3000/auth/request-password-reset
Content-Type: application/json

{
  "email": "lucas1511gll@gmail.com"
}

### Auth reset password
POST http://localhost:3000/auth/reset-password
Content-Type: application/json

{
  "token": "3dc984bd-6c5c-4b32-8504-3820b90a90a1",
  "password": "123456",
  "confirmPassword": "123456"
}

### Auth verify email
POST http://localhost:3000/auth/verify-email
Content-Type: application/json

{
  "token": "282b1da8-2013-4187-8923-ec29adedfc98"
}

### Auth logout
POST http://localhost:3000/auth/logout
Content-Type: application/json

{
  "refreshToken": "4d75ea5c-7b83-458e-a6cd-f3e4508f4343"
}



